version: '3.8'

services:
  # PostgreSQL
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Riham1234
      POSTGRES_DB: smarthome_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - smarthome_net

  # MongoDB
  mongodb:
    image: mongo:latest
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - smarthome_net

  # InfluxDB
  influxdb:
    image: influxdb:latest
    container_name: influx_db
    restart: always
    ports:
      - "8086:8086"
    volumes:
      - influx_data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=reham
      - DOCKER_INFLUXDB_INIT_PASSWORD=reham_password
      - DOCKER_INFLUXDB_INIT_ORG=myhome
      - DOCKER_INFLUXDB_INIT_BUCKET=sensors_data
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my_super_secret_token
    networks:
      - smarthome_net

  
networks:
  smarthome_net:
    driver: bridge

volumes:
  postgres_data:
  mongo_data:
  influx_data:
  